name: ML Model Retraining CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/IndonesiaWorkfare_preprocessing.csv"
  TARGET_VAR: "CI"

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python and Conda
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Check Env
        run: |
            echo $CSV_URL
      # install mlflow
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install mlflow
      # run as a mlflow project
      - name: Run MLflow Project for Retraining
        run: |
            mlflow run MLproject --env-manager=local

      # get latest run id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
      - name: Commit and Push New Artifacts
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull --rebase
          git add -A
          # Cek jika ada perubahan, jika tidak, keluar
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated: Retrain model and update artifacts"
          git push
      #Build docker model
      - name: Build Docker Model
        run: |
            mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"
      
      # login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      
      # Tag the docker image
      - name: Tag Docker Image
        run: |
            docker tag cc ${{ secrets.DOCKER_HUB_USERNAME}}/cc:latest
      # push docker image to docker hub
      - name: Push Docker Image
        run: |
            docker push ${{ secrets.DOCKER_HUB_USERNAME}}/cc:latest